###############################################################################
#    Copyright (C) 2019 Dejan Priversek
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the-
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
###############################################################################

# PadFunction: IO_L12P_T1_MRCC_14
set_property IOSTANDARD LVDS_25 [get_ports clk_adc_p]

# PadFunction: IO_L12N_T1_MRCC_14
set_property IOSTANDARD LVDS_25 [get_ports clk_adc_n]
set_property PACKAGE_PIN N14 [get_ports clk_adc_p]
set_property PACKAGE_PIN P14 [get_ports clk_adc_n]

# place ports

set_property IOSTANDARD LVDS_25 [get_ports {data_p[13]}]
set_property IOSTANDARD LVDS_25 [get_ports {data_p[12]}]
set_property IOSTANDARD LVDS_25 [get_ports {data_p[11]}]
set_property IOSTANDARD LVDS_25 [get_ports {data_p[10]}]
set_property IOSTANDARD LVDS_25 [get_ports {data_p[9]}]
set_property IOSTANDARD LVDS_25 [get_ports {data_p[8]}]
set_property IOSTANDARD LVDS_25 [get_ports {data_p[7]}]
set_property IOSTANDARD LVDS_25 [get_ports {data_p[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {data_p[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {data_p[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {data_p[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {data_p[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {data_p[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {data_p[0]}]

set_property PACKAGE_PIN P10 [get_ports {data_p[0]}]
set_property PACKAGE_PIN P11 [get_ports {data_n[0]}]
set_property PACKAGE_PIN R13 [get_ports {data_p[1]}]
set_property PACKAGE_PIN T13 [get_ports {data_n[1]}]
set_property PACKAGE_PIN K15 [get_ports {data_p[2]}]
set_property PACKAGE_PIN K16 [get_ports {data_n[2]}]
set_property PACKAGE_PIN L14 [get_ports {data_p[3]}]
set_property PACKAGE_PIN M14 [get_ports {data_n[3]}]
set_property PACKAGE_PIN K13 [get_ports {data_p[4]}]
set_property PACKAGE_PIN L13 [get_ports {data_n[4]}]
set_property PACKAGE_PIN R15 [get_ports {data_p[5]}]
set_property PACKAGE_PIN R16 [get_ports {data_n[5]}]
set_property PACKAGE_PIN T14 [get_ports {data_p[6]}]
set_property PACKAGE_PIN T15 [get_ports {data_n[6]}]
set_property PACKAGE_PIN P15 [get_ports {data_p[7]}]
set_property PACKAGE_PIN P16 [get_ports {data_n[7]}]
set_property PACKAGE_PIN R10 [get_ports {data_p[8]}]
set_property PACKAGE_PIN R11 [get_ports {data_n[8]}]
set_property PACKAGE_PIN M16 [get_ports {data_p[9]}]
set_property PACKAGE_PIN N16 [get_ports {data_n[9]}]
set_property PACKAGE_PIN N9 [get_ports {data_p[10]}]
set_property PACKAGE_PIN P9 [get_ports {data_n[10]}]
set_property PACKAGE_PIN M6 [get_ports {data_p[11]}]
set_property PACKAGE_PIN N6 [get_ports {data_n[11]}]
set_property PACKAGE_PIN R5 [get_ports {data_p[12]}]
set_property PACKAGE_PIN T5 [get_ports {data_n[12]}]
set_property PACKAGE_PIN T9 [get_ports {data_p[13]}]
set_property PACKAGE_PIN T10 [get_ports {data_n[13]}]

set_property IOSTANDARD LVCMOS18 [get_ports ch2_k]
set_property IOSTANDARD LVCMOS18 [get_ports ch1_k]
set_property IOSTANDARD LVCMOS18 [get_ports adcA_cs]
set_property IOSTANDARD LVCMOS18 [get_ports adc_sclk]
set_property IOSTANDARD LVCMOS18 [get_ports adc_sdin]
set_property IOSTANDARD LVCMOS18 [get_ports {faddr[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {faddr[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {LED[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}]

set_property IOSTANDARD LVCMOS18 [get_ports {fdata[31]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[30]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[29]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[28]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[27]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[26]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[25]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[24]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[23]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[22]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[21]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[20]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[19]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[18]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[17]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[16]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fdata[0]}]

set_property IOSTANDARD LVCMOS18 [get_ports clk_fx3]
set_property IOSTANDARD LVCMOS18 [get_ports ch1_dc]
set_property IOSTANDARD LVCMOS18 [get_ports ch2_dc]
set_property IOSTANDARD LVCMOS18 [get_ports flaga]
set_property IOSTANDARD LVCMOS18 [get_ports flagb]
set_property IOSTANDARD LVCMOS18 [get_ports flagd]
set_property IOSTANDARD LVCMOS18 [get_ports ch1_gnd]
set_property IOSTANDARD LVCMOS18 [get_ports ch2_gnd]
set_property IOSTANDARD LVCMOS18 [get_ports an_trig_level]
set_property IOSTANDARD LVCMOS18 [get_ports slrd_sloe]
set_property IOSTANDARD LVCMOS18 [get_ports slwr]
set_property IOSTANDARD LVCMOS18 [get_ports slcs]
set_property IOSTANDARD LVCMOS18 [get_ports pktend]
set_property PACKAGE_PIN T8 [get_ports adc_sdin]
set_property PACKAGE_PIN R8 [get_ports adc_sclk]
set_property PACKAGE_PIN T7 [get_ports adcA_cs]


set_property PACKAGE_PIN C1 [get_ports clk_fx3]
set_property PACKAGE_PIN T12 [get_ports an_trig_level]
set_property PACKAGE_PIN N12 [get_ports ch2_dc]
set_property PACKAGE_PIN R12 [get_ports ch1_dc]
set_property PACKAGE_PIN M12 [get_ports ch1_gnd]
set_property PACKAGE_PIN N13 [get_ports ch2_gnd]


set_property PACKAGE_PIN M15 [get_ports ch2_k]
set_property PACKAGE_PIN P13 [get_ports ch1_k]
set_property PACKAGE_PIN L5 [get_ports {LED[2]}]
set_property PACKAGE_PIN M5 [get_ports {LED[3]}]
set_property PACKAGE_PIN L4 [get_ports {LED[1]}]

set_property PACKAGE_PIN H2 [get_ports {fdata[25]}]
set_property PACKAGE_PIN H5 [get_ports {fdata[24]}]
set_property PACKAGE_PIN F5 [get_ports {fdata[23]}]
set_property PACKAGE_PIN G1 [get_ports {fdata[22]}]
set_property PACKAGE_PIN F4 [get_ports {fdata[20]}]
set_property PACKAGE_PIN A2 [get_ports {fdata[14]}]
set_property PACKAGE_PIN A4 [get_ports {fdata[12]}]
set_property PACKAGE_PIN A3 [get_ports {fdata[11]}]
set_property PACKAGE_PIN A5 [get_ports {fdata[10]}]
set_property PACKAGE_PIN D4 [get_ports {fdata[9]}]
set_property PACKAGE_PIN D5 [get_ports {fdata[8]}]
set_property PACKAGE_PIN B4 [get_ports {fdata[7]}]
set_property PACKAGE_PIN B6 [get_ports {fdata[6]}]
set_property PACKAGE_PIN B5 [get_ports {fdata[5]}]
set_property PACKAGE_PIN C7 [get_ports {fdata[4]}]
set_property PACKAGE_PIN B7 [get_ports {fdata[3]}]
set_property PACKAGE_PIN J5 [get_ports {fdata[2]}]
set_property PACKAGE_PIN D6 [get_ports {fdata[1]}]
set_property PACKAGE_PIN A7 [get_ports {fdata[0]}]
set_property PACKAGE_PIN B2 [get_ports {fdata[13]}]
set_property PACKAGE_PIN C6 [get_ports {fdata[15]}]
set_property PACKAGE_PIN E2 [get_ports {fdata[16]}]
set_property PACKAGE_PIN E6 [get_ports {fdata[17]}]
set_property PACKAGE_PIN E1 [get_ports {fdata[18]}]
set_property PACKAGE_PIN F2 [get_ports {fdata[19]}]
set_property PACKAGE_PIN G2 [get_ports {fdata[21]}]
set_property PACKAGE_PIN J4 [get_ports {fdata[26]}]
set_property PACKAGE_PIN H4 [get_ports {fdata[27]}]
set_property PACKAGE_PIN G4 [get_ports {fdata[28]}]
set_property PACKAGE_PIN H1 [get_ports {fdata[29]}]
set_property PACKAGE_PIN G5 [get_ports {fdata[30]}]
set_property PACKAGE_PIN H3 [get_ports {fdata[31]}]
set_property PACKAGE_PIN D1 [get_ports {faddr[1]}]
set_property PACKAGE_PIN F3 [get_ports {faddr[0]}]
set_property PACKAGE_PIN D3 [get_ports flaga]
set_property PULLDOWN true [get_ports flaga]
set_property PACKAGE_PIN E5 [get_ports flagb]
set_property PULLDOWN true [get_ports flagb]
set_property PACKAGE_PIN E3 [get_ports flagd]
set_property PULLUP true [get_ports flagd]
set_property PACKAGE_PIN C3 [get_ports slrd_sloe]
set_property PACKAGE_PIN C2 [get_ports slwr]
set_property PACKAGE_PIN B1 [get_ports slcs]
set_property PACKAGE_PIN C4 [get_ports pktend]

set_property IOSTANDARD LVDS_25 [get_ports an_trig_p]
set_property IOSTANDARD LVDS_25 [get_ports an_trig_n]
set_property PACKAGE_PIN R6 [get_ports an_trig_p]
set_property PACKAGE_PIN R7 [get_ports an_trig_n]

set_property BEL A6LUT [get_cells lut_delay_inst/LUT_0]
set_property LOC SLICE_X8Y0 [get_cells lut_delay_inst/LUT_0]
set_property BEL AFF [get_cells lut_delay_inst/FDRE0_inst_0]
set_property LOC SLICE_X8Y0 [get_cells lut_delay_inst/FDRE0_inst_0]
set_property BEL B6LUT [get_cells lut_delay_inst/LUT_1]
set_property LOC SLICE_X8Y0 [get_cells lut_delay_inst/LUT_1]
set_property BEL BFF [get_cells lut_delay_inst/FDRE0_inst_1]
set_property LOC SLICE_X8Y0 [get_cells lut_delay_inst/FDRE0_inst_1]
set_property BEL C6LUT [get_cells lut_delay_inst/LUT_2]
set_property LOC SLICE_X8Y0 [get_cells lut_delay_inst/LUT_2]
set_property BEL CFF [get_cells lut_delay_inst/FDRE0_inst_2]
set_property LOC SLICE_X8Y0 [get_cells lut_delay_inst/FDRE0_inst_2]
set_property BEL D6LUT [get_cells lut_delay_inst/LUT_3]
set_property LOC SLICE_X8Y0 [get_cells lut_delay_inst/LUT_3]
set_property BEL DFF [get_cells lut_delay_inst/FDRE0_inst_3]
set_property LOC SLICE_X8Y0 [get_cells lut_delay_inst/FDRE0_inst_3]

set_property BEL A6LUT [get_cells lut_delay_inst/LUT_4]
set_property LOC SLICE_X8Y1 [get_cells lut_delay_inst/LUT_4]
set_property BEL AFF [get_cells lut_delay_inst/FDRE0_inst_4]
set_property LOC SLICE_X8Y1 [get_cells lut_delay_inst/FDRE0_inst_4]
set_property BEL B6LUT [get_cells lut_delay_inst/LUT_5]
set_property LOC SLICE_X8Y1 [get_cells lut_delay_inst/LUT_5]
set_property BEL BFF [get_cells lut_delay_inst/FDRE0_inst_5]
set_property LOC SLICE_X8Y1 [get_cells lut_delay_inst/FDRE0_inst_5]
set_property BEL C6LUT [get_cells lut_delay_inst/LUT_6]
set_property LOC SLICE_X8Y1 [get_cells lut_delay_inst/LUT_6]
set_property BEL CFF [get_cells lut_delay_inst/FDRE0_inst_6]
set_property LOC SLICE_X8Y1 [get_cells lut_delay_inst/FDRE0_inst_6]
set_property BEL D6LUT [get_cells lut_delay_inst/LUT_7]
set_property LOC SLICE_X8Y1 [get_cells lut_delay_inst/LUT_7]
set_property BEL DFF [get_cells lut_delay_inst/FDRE0_inst_7]
set_property LOC SLICE_X8Y1 [get_cells lut_delay_inst/FDRE0_inst_7]

set_property BEL A6LUT [get_cells lut_delay_inst/LUT_8]
set_property LOC SLICE_X8Y2 [get_cells lut_delay_inst/LUT_8]
set_property BEL AFF [get_cells lut_delay_inst/FDRE0_inst_8]
set_property LOC SLICE_X8Y2 [get_cells lut_delay_inst/FDRE0_inst_8]
set_property BEL B6LUT [get_cells lut_delay_inst/LUT_9]
set_property LOC SLICE_X8Y2 [get_cells lut_delay_inst/LUT_9]
set_property BEL BFF [get_cells lut_delay_inst/FDRE0_inst_9]
set_property LOC SLICE_X8Y2 [get_cells lut_delay_inst/FDRE0_inst_9]
set_property BEL C6LUT [get_cells lut_delay_inst/LUT_10]
set_property LOC SLICE_X8Y2 [get_cells lut_delay_inst/LUT_10]
set_property BEL CFF [get_cells lut_delay_inst/FDRE0_inst_10]
set_property LOC SLICE_X8Y2 [get_cells lut_delay_inst/FDRE0_inst_10]
set_property BEL D6LUT [get_cells lut_delay_inst/LUT_11]
set_property LOC SLICE_X8Y2 [get_cells lut_delay_inst/LUT_11]
set_property BEL DFF [get_cells lut_delay_inst/FDRE0_inst_11]
set_property LOC SLICE_X8Y2 [get_cells lut_delay_inst/FDRE0_inst_11]

set_property BEL A6LUT [get_cells lut_delay_inst/LUT_12]
set_property LOC SLICE_X8Y3 [get_cells lut_delay_inst/LUT_12]
set_property BEL AFF [get_cells lut_delay_inst/FDRE0_inst_12]
set_property LOC SLICE_X8Y3 [get_cells lut_delay_inst/FDRE0_inst_12]
set_property BEL B6LUT [get_cells lut_delay_inst/LUT_13]
set_property LOC SLICE_X8Y3 [get_cells lut_delay_inst/LUT_13]
set_property BEL BFF [get_cells lut_delay_inst/FDRE0_inst_13]
set_property LOC SLICE_X8Y3 [get_cells lut_delay_inst/FDRE0_inst_13]
set_property BEL C6LUT [get_cells lut_delay_inst/LUT_14]
set_property LOC SLICE_X8Y3 [get_cells lut_delay_inst/LUT_14]
set_property BEL CFF [get_cells lut_delay_inst/FDRE0_inst_14]
set_property LOC SLICE_X8Y3 [get_cells lut_delay_inst/FDRE0_inst_14]
set_property BEL D6LUT [get_cells lut_delay_inst/LUT_15]
set_property LOC SLICE_X8Y3 [get_cells lut_delay_inst/LUT_15]
set_property BEL DFF [get_cells lut_delay_inst/FDRE0_inst_15]
set_property LOC SLICE_X8Y3 [get_cells lut_delay_inst/FDRE0_inst_15]

set_property BEL A6LUT [get_cells lut_delay_inst/LUT_16]
set_property LOC SLICE_X8Y4 [get_cells lut_delay_inst/LUT_16]
set_property BEL AFF [get_cells lut_delay_inst/FDRE0_inst_16]
set_property LOC SLICE_X8Y4 [get_cells lut_delay_inst/FDRE0_inst_16]
set_property BEL B6LUT [get_cells lut_delay_inst/LUT_17]
set_property LOC SLICE_X8Y4 [get_cells lut_delay_inst/LUT_17]
set_property BEL BFF [get_cells lut_delay_inst/FDRE0_inst_17]
set_property LOC SLICE_X8Y4 [get_cells lut_delay_inst/FDRE0_inst_17]
set_property BEL C6LUT [get_cells lut_delay_inst/LUT_18]
set_property LOC SLICE_X8Y4 [get_cells lut_delay_inst/LUT_18]
set_property BEL CFF [get_cells lut_delay_inst/FDRE0_inst_18]
set_property LOC SLICE_X8Y4 [get_cells lut_delay_inst/FDRE0_inst_18]
set_property BEL D6LUT [get_cells lut_delay_inst/LUT_19]
set_property LOC SLICE_X8Y4 [get_cells lut_delay_inst/LUT_19]
set_property BEL DFF [get_cells lut_delay_inst/FDRE0_inst_19]
set_property LOC SLICE_X8Y4 [get_cells lut_delay_inst/FDRE0_inst_19]

set_property BEL A6LUT [get_cells lut_delay_inst/LUT_20]
set_property LOC SLICE_X8Y5 [get_cells lut_delay_inst/LUT_20]
set_property BEL AFF [get_cells lut_delay_inst/FDRE0_inst_20]
set_property LOC SLICE_X8Y5 [get_cells lut_delay_inst/FDRE0_inst_20]
set_property BEL B6LUT [get_cells lut_delay_inst/LUT_21]
set_property LOC SLICE_X8Y5 [get_cells lut_delay_inst/LUT_21]
set_property BEL BFF [get_cells lut_delay_inst/FDRE0_inst_21]
set_property LOC SLICE_X8Y5 [get_cells lut_delay_inst/FDRE0_inst_21]
set_property BEL C6LUT [get_cells lut_delay_inst/LUT_22]
set_property LOC SLICE_X8Y5 [get_cells lut_delay_inst/LUT_22]
set_property BEL CFF [get_cells lut_delay_inst/FDRE0_inst_22]
set_property LOC SLICE_X8Y5 [get_cells lut_delay_inst/FDRE0_inst_22]
set_property BEL D6LUT [get_cells lut_delay_inst/LUT_23]
set_property LOC SLICE_X8Y5 [get_cells lut_delay_inst/LUT_23]
set_property BEL DFF [get_cells lut_delay_inst/FDRE0_inst_23]
set_property LOC SLICE_X8Y5 [get_cells lut_delay_inst/FDRE0_inst_23]

set_property BEL A6LUT [get_cells lut_delay_inst/LUT_24]
set_property LOC SLICE_X8Y6 [get_cells lut_delay_inst/LUT_24]
set_property BEL AFF [get_cells lut_delay_inst/FDRE0_inst_24]
set_property LOC SLICE_X8Y6 [get_cells lut_delay_inst/FDRE0_inst_24]
set_property BEL B6LUT [get_cells lut_delay_inst/LUT_25]
set_property LOC SLICE_X8Y6 [get_cells lut_delay_inst/LUT_25]
set_property BEL BFF [get_cells lut_delay_inst/FDRE0_inst_25]
set_property LOC SLICE_X8Y6 [get_cells lut_delay_inst/FDRE0_inst_25]
set_property BEL C6LUT [get_cells lut_delay_inst/LUT_26]
set_property LOC SLICE_X8Y6 [get_cells lut_delay_inst/LUT_26]
set_property BEL CFF [get_cells lut_delay_inst/FDRE0_inst_26]
set_property LOC SLICE_X8Y6 [get_cells lut_delay_inst/FDRE0_inst_26]
set_property BEL D6LUT [get_cells lut_delay_inst/LUT_27]
set_property LOC SLICE_X8Y6 [get_cells lut_delay_inst/LUT_27]
set_property BEL DFF [get_cells lut_delay_inst/FDRE0_inst_27]
set_property LOC SLICE_X8Y6 [get_cells lut_delay_inst/FDRE0_inst_27]

set_property BEL A6LUT [get_cells lut_delay_inst/LUT_28]
set_property LOC SLICE_X8Y7 [get_cells lut_delay_inst/LUT_28]
set_property BEL AFF [get_cells lut_delay_inst/FDRE0_inst_28]
set_property LOC SLICE_X8Y7 [get_cells lut_delay_inst/FDRE0_inst_28]
set_property BEL B6LUT [get_cells lut_delay_inst/LUT_29]
set_property LOC SLICE_X8Y7 [get_cells lut_delay_inst/LUT_29]
set_property BEL BFF [get_cells lut_delay_inst/FDRE0_inst_29]
set_property LOC SLICE_X8Y7 [get_cells lut_delay_inst/FDRE0_inst_29]
set_property BEL C6LUT [get_cells lut_delay_inst/LUT_30]
set_property LOC SLICE_X8Y7 [get_cells lut_delay_inst/LUT_30]
set_property BEL CFF [get_cells lut_delay_inst/FDRE0_inst_30]
set_property LOC SLICE_X8Y7 [get_cells lut_delay_inst/FDRE0_inst_30]
set_property BEL D6LUT [get_cells lut_delay_inst/LUT_31]
set_property LOC SLICE_X8Y7 [get_cells lut_delay_inst/LUT_31]
set_property BEL DFF [get_cells lut_delay_inst/FDRE0_inst_31]
set_property LOC SLICE_X8Y7 [get_cells lut_delay_inst/FDRE0_inst_31]
